title: NELLAB Wiki
description: A wiki for Nellab

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache

collections:
  docs:
    output: true

defaults:
  - scope:
      path: "docs"
    values:
      layout: "default"

includes:
  - css/custom.css

markdown: kramdown
highlighter: rouge
