title: Just the Docs Template
description: A starter template for a Jekyll site using the Just the Docs theme!

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

collections:
  docs:
    output: true

defaults:
  - scope:
      path: "docs"
    values:
      layout: "default"

includes:
  - css/custom.css
